import Papa from 'papaparse'

const mockInventoryData = [
  { sku: '111244', description: 'Benebone Rubber Bone Small', available: 714, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '111244ML', description: 'Benebone Product', available: 262, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '112244', description: 'Benebone Rubber Bone Medium', available: 792, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '112244ML', description: 'Benebone Product', available: 221, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '113244', description: 'Benebone Rubber Bone Large', available: 391, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '113244ML', description: 'Benebone Product', available: 320, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '121244', description: 'Benebone Rubber Ball', available: 419, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '121244ML', description: 'Benebone Product', available: 198, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '130244', description: 'Benebone Rubber Tug (Flat)', available: 747, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '131122', description: 'Benebone Rubber Tug (Ball)', available: 550, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '131122ML', description: 'Benebone Product', available: 345, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '141122', description: 'Benebone Rubber Cone', available: 207, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '141122ML', description: 'Benebone Product', available: 290, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '150122', description: 'Benebone Product', available: 821, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '150122ML', description: 'Benebone Product', available: 347, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '151122', description: 'Benebone Product', available: 949, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '151122ML', description: 'Benebone Product', available: 366, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '231240', description: 'Benebone Product', available: 108, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '231244', description: 'Benebone Product', available: 537, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '232060', description: 'Benebone Treat Pod - Bacon 9ct', available: 52, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '233060', description: 'Benebone Treat Pod - Peanut 9ct', available: 365, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '236080', description: 'Benebone Tongue Twister / Bacon Treat Pod 2PK', available: 161, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '237080', description: 'Benebone Tongue Twister / Peanut Treat Pod 2PK', available: 121, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '301244', description: 'Benebone Product', available: 3866, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '302244', description: 'Benebone Product', available: 2110, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '302244EF', description: 'Benebone Product', available: 314, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '303244', description: 'Benebone Product', available: 3115, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '304244', description: 'Benebone Product', available: 1330, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '304244EF', description: 'Benebone Product', available: 103, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '305244', description: 'Benebone Product', available: 3032, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '305244EF', description: 'Benebone Product', available: 55, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '306244', description: 'Benebone Product', available: 6067, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '306244EF', description: 'Benebone Product', available: 135, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '307244', description: 'Benebone Product', available: 754, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '308122', description: 'Benebone Product', available: 762, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '309244', description: 'Benebone Essentials Tug Medium', available: 197, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '310150', description: 'Benebone Product', available: 120, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '310244', description: 'Benebone Product', available: 3046, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '311100', description: 'Benebone Product', available: 180, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '312300', description: 'Benebone Product', available: 50, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '313150', description: 'Benebone Product', available: 110, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '314100', description: 'Benebone Product', available: 172, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '315', description: 'LBL21126 Benebone Essentials Fishbone Small', available: 2000, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '315400', description: 'Benebone Product', available: 110, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '316', description: 'LBL21127 Benebone Essentials Fishbone Large', available: 1000, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '316200', description: 'Benebone Product', available: 80, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '317', description: 'LBL21128 Benebone Essentials Fishbone Giant', available: 1000, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '317150', description: 'Benebone Product', available: 50, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '318300', description: 'Benebone Product', available: 72, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '319150', description: 'Benebone Product', available: 110, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '321100', description: 'Benebone Product', available: 79, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '322200', description: 'Benebone Product', available: 21, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '323244', description: 'Benebone Product', available: 2149, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '324244', description: 'Benebone Product', available: 3550, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '326244', description: 'Benebone Essentials Tongue Twister Medium 24/4PK', available: 108, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '327060', description: 'Benebone Essentials Treat Pod - Bacon 6ct', available: 815, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '410244', description: 'Benebone Fishbone Small 24/4PK', available: 46, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '410244ML', description: 'Benebone Product', available: 123, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '410300', description: 'Benebone Product', available: 908, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '420244', description: 'Benebone Fishbone Medium 24/4PK', available: 2003, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '420244ML', description: 'Benebone Product', available: 525, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '420244T', description: 'Benebone Product', available: 235, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '420300', description: 'Benebone Fishbone Medium 30PK', available: 315, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '420300V', description: 'Benebone Product', available: 168, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '430244', description: 'Benebone Product', available: 142, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '430244ML', description: 'Benebone Product', available: 143, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '430300', description: 'Benebone Product', available: 505, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '440244', description: 'Benebone Fishbone Giant 24/4PK', available: 30, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '440244ML', description: 'Benebone Product', available: 50, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '440250', description: 'Benebone Product', available: 316, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '451244', description: 'Benebone Green Fishbone Eco Bone Small 24/4PK', available: 1093, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '451244ML', description: 'Benebone Product', available: 0, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '452244', description: 'Benebone Green Fishbone Eco Bone Medium 24/4PK', available: 942, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '452244ML', description: 'Benebone Product', available: 0, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '453244', description: 'Benebone Green Fishbone Eco Bone Large 24/4PK', available: 472, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '453244ML', description: 'Benebone Product', available: 0, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '501008', description: 'Benebone Product', available: 13063, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '501008-BLU', description: 'Benebone Product', available: 262, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '502008', description: 'Benebone Product', available: 3669, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '502008-BLU', description: 'Benebone Product', available: 83, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '503008', description: 'Benebone Product', available: 8906, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '503008-BLU', description: 'Benebone Product', available: 98, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '504080', description: 'Benebone 4-Pack WB/FB/MS/ZG Puppy', available: 688, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '507080', description: 'Benebone Product', available: 84, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '508080', description: 'Benebone Product', available: 1416, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '509', description: 'LBL21091 Benebone 4-Pack Rubber Ball', available: 1000, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '509100', description: 'Benebone Product', available: 37, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '510200', description: 'Benebone Product', available: 643, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '510244', description: 'Benebone Product', available: 64, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '510244ML', description: 'Benebone Product', available: 17, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '511', description: 'LBL21129 Benebone 3-Pack Wishbone Small 20PK', available: 1000, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '511200', description: 'Benebone Product', available: 341, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '512', description: 'LBL21130 Benebone 3-Pack Wishbone Medium 15PK', available: 2000, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '512150', description: 'Benebone 3-Pack Wishbone Medium 15PK', available: 393, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '513', description: 'LBL21131 Benebone 3-Pack Wishbone Large 10PK', available: 1000, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '513100', description: 'Benebone Product', available: 418, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '514080', description: 'Benebone 7-Pack Medium', available: 777, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '518080', description: 'Benebone Product', available: 0, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '520244', description: 'Benebone Product', available: 1951, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '520244ML', description: 'Benebone Product', available: 106, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '520350', description: 'Benebone Product', available: 823, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '530244', description: 'Benebone Product', available: 45, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '530244ML', description: 'Benebone Product', available: 1, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '530300', description: 'Benebone Product', available: 178, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '540200', description: 'Benebone Tripe Bone Giant 20PK', available: 17, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '540244', description: 'Benebone Product', available: 64, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '551244', description: 'Benebone Product', available: 205, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '552244', description: 'Benebone Product', available: 504, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '553244', description: 'Benebone Product', available: 349, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '560200', description: 'Benebone Product', available: 660, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '560244', description: 'Benebone Product', available: 118, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '560244ML', description: 'Benebone Product', available: 75, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '561244', description: 'Benebone Ring Peppermint Small 24/4PK', available: 171, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '570244', description: 'Benebone Ring Bacon Medium 24/4PK', available: 1656, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '570244ML', description: 'Benebone Product', available: 27, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '570244T', description: 'Benebone Product', available: 138, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '570300', description: 'Benebone Product', available: 1035, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '571244', description: 'Benebone Ring Peppermint Medium 24/4PK', available: 78, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '580200', description: 'Benebone Product', available: 688, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '580244', description: 'Benebone Product', available: 74, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '580244ML', description: 'Benebone Product', available: 2, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '581244', description: 'Benebone Ring Peppermint Large 24/4PK', available: 2, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '610244', description: 'Benebone Product', available: 95, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '610300', description: 'Benebone Product', available: 277, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '611300', description: 'Benebone Product', available: 2, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '620244', description: 'Benebone Product', available: 75, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '620400', description: 'Benebone Product', available: 394, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '630244', description: 'Benebone Product', available: 52, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '630250', description: 'Benebone Product', available: 151, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '631250', description: 'Benebone Product', available: 8, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '635244', description: 'Benebone Product', available: 132, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '635250', description: 'Benebone Product', available: 127, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '640244', description: 'Benebone Product', available: 1325, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '640244ML', description: 'Benebone Product', available: 482, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '640400', description: 'Benebone Puppy 2-Pack Dental Chew/Wishbone Bacon Tiny 40PK', available: 690, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '641', description: 'LBL21090 Benebone 2-Pack Rubber Ball (641', available: 2000, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '641150', description: 'Benebone Product', available: 172, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '642200', description: 'Benebone Product', available: 1471, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '642244', description: 'Benebone Product', available: 31, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '643', description: 'LBL21092 Benebone 2-Pack Bacon Wishbone / Rubber Bone Medium (643)', available: 2000, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '643100', description: 'Benebone Product', available: 193, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '644', description: 'LBL21133 Benebone Puppy 2-Pack Dental Chew/Wishbone Bacon Small 15PK', available: 1000, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '644150', description: 'Benebone Product', available: 143, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '645244', description: 'Benebone Product', available: 74, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '645244ML', description: 'Benebone Product', available: 81, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '645400', description: 'Benebone 2-Pack Dental Chew/Wishbone Bacon Tiny 40PK', available: 269, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '646', description: 'LBL21134 Benebone Puppy 2-Pack Dental Chew/Wishbone Chicken Tiny 40PK', available: 2000, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '646400', description: 'Benebone Product', available: 67, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '647150', description: 'Benebone Product', available: 74, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '650244', description: 'Benebone Product', available: 1402, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '650244ML', description: 'Benebone Product', available: 465, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '650400', description: 'Benebone Puppy 2-Pack Maplestick/Zaggler Bacon Tiny 40PK', available: 204, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '655244', description: 'Benebone Product', available: 51, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '655244ML', description: 'Benebone Product', available: 45, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '655400', description: 'Benebone 2-Pack Maplestick/Zaggler Bacon Tiny 40PK', available: 122, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '660244', description: 'Benebone Product', available: 39, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '660244ML', description: 'Benebone Product', available: 53, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '660400', description: 'Benebone Puppy 2-Pack Fishbone Tiny 40PK', available: 234, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '661244', description: 'Benebone 2-Pack Wishbone Bacon & Chicken Medium', available: 0, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '662200', description: 'Benebone Product', available: 674, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '662244', description: 'Benebone Product', available: 1228, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '665244', description: 'Benebone Product', available: 64, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '665244ML', description: 'Benebone Product', available: 191, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '665400', description: 'Benebone 2-Pack Fishbone Tiny 40PK', available: 114, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '670244', description: 'Benebone Puppy 2-Pack Rubber Bone/Wishbone Bacon Tiny 24/4PK', available: 426, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '670244ML', description: 'Benebone Product', available: 81, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '670400', description: 'Benebone Product', available: 335, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '671', description: 'LBL21042 Benebone 2-Pack Wishbone / Dental Chew Small (671)', available: 7000, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '671100', description: 'Benebone Product', available: 317, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '672', description: 'LBL21043 Benebone 2-Pack Wishbone / Dental Chew Medium (672)', available: 6000, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '672080', description: 'Benebone Product', available: 1299, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '673080', description: 'Benebone Product', available: 1936, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '674', description: 'LBL21045 Benebone 2-Pack Wishbone / Fishbone Small (674)', available: 5000, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '674100', description: 'Benebone Product', available: 391, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '675', description: 'LBL21046 Benebone 2-Pack Wishbone / Fishbone Medium (675)', available: 7500, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '675080', description: 'Benebone Product', available: 1316, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '676', description: 'LBL21047 Benebone 2-Pack Wishbone / Fishbone Large (676)', available: 4000, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '676080', description: 'Benebone Product', available: 334, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '677', description: 'LBL21048 Benebone 2-Pack Maplestick / Zaggler Small (677)', available: 2000, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '677080', description: 'Benebone Product', available: 127, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '678060', description: 'Benebone Product', available: 322, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '679', description: 'LBL21050 Benebone 2-Pack Maplestick / Zaggler Large (679)', available: 6000, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '679060', description: 'Benebone Product', available: 698, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '680100', description: 'Benebone 2-Pack Wishbone Bacon Small', available: 81, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '681080', description: 'Benebone 2-Pack Wishbone Bacon Medium', available: 85, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '682060', description: 'Benebone 2-Pack Wishbone Bacon Large', available: 1, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '685244', description: 'Benebone Product', available: 37, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '685400', description: 'Benebone Product', available: 65, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '721244', description: 'Benebone Product', available: 434, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '722244', description: 'Benebone Product', available: 1625, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '723244', description: 'Benebone Product', available: 730, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '724244', description: 'Benebone Product', available: 782, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '801244', description: 'Benebone Product', available: 111, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '801244ML', description: 'Benebone Product', available: 56, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '801300', description: 'Benebone Product', available: 305, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '802244', description: 'Benebone Product', available: 1418, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '802244ML', description: 'Benebone Product', available: 32, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '802350', description: 'Benebone Product', available: 428, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '803244', description: 'Benebone Product', available: 87, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '803244ML', description: 'Benebone Product', available: 48, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '803300', description: 'Benebone Product', available: 338, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '804244', description: 'Benebone Product', available: 110, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '804300', description: 'Benebone Product', available: 479, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '805244', description: 'Benebone Maplestick Giant 24/4PK', available: 11, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '805300', description: 'Benebone Maplestick Giant 30PK', available: 46, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '807', description: 'LBL21052 Benebone Tiny Wishbone (807)', available: 12000, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '807200', description: 'Benebone Product', available: 1275, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '807244', description: 'Benebone Product', available: 202, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '808244', description: 'Benebone Wishbone Bacon Medium 24/4PK', available: 3837, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '808244ML', description: 'Benebone Product', available: 605, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '808244T', description: 'Benebone Product', available: 163, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '808600', description: 'Benebone Wishbone Bacon Medium 60PK', available: 3174, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '808600X', description: 'Benebone Product', available: 405, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '809244', description: 'Benebone Product', available: 66, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '809244ML', description: 'Benebone Product', available: 98, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '809600', description: 'Benebone Puppy Wishbone Bacon Medium 60PK', available: 57, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '810244', description: 'Benebone Product', available: 357, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '811244', description: 'Benebone Product', available: 87, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '811244ML', description: 'Benebone Product', available: 238, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '811300', description: 'Benebone Bacon Stick Small 30PK', available: 195, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '812244', description: 'Benebone Product', available: 279, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '812244ML', description: 'Benebone Product', available: 337, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '812350', description: 'Benebone Product', available: 820, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '813244', description: 'Benebone Product', available: 69, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '813244ML', description: 'Benebone Product', available: 267, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '813300', description: 'Benebone Product', available: 364, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '814244', description: 'Benebone Bacon Stick Giant 24/4PK', available: 2, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '814300', description: 'Benebone Product', available: 170, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '818244', description: 'Benebone Wishbone Peanut Medium 24/4PK', available: 66, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '818244ML', description: 'Benebone Product', available: 196, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '818600', description: 'Benebone Product', available: 756, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '820244', description: 'Benebone Wishbone Chicken Medium 24/4PK', available: 86, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '820244ML', description: 'Benebone Product', available: 473, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '820600', description: 'Benebone Wishbone Chicken Medium 60PK', available: 513, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '820600X', description: 'Benebone Product', available: 90, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '821244', description: 'Benebone Product', available: 116, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '823244', description: 'Benebone Product', available: 203, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '825244', description: 'Benebone Product', available: 67, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '825300', description: 'Benebone Product', available: 55, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '828244', description: 'Benebone Wishbone Bacon Small 24/4PK', available: 1520, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '828244ML', description: 'Benebone Product', available: 390, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '828244T', description: 'Benebone Product', available: 437, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '828500', description: 'Benebone Wishbone Bacon Small 50PK', available: 1637, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '828500X', description: 'Benebone Product', available: 560, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '829244', description: 'Benebone Product', available: 411, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '829244ML', description: 'Benebone Product', available: 336, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '829500', description: 'Benebone Product', available: 425, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '830244', description: 'Benebone Product', available: 66, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '830400', description: 'Benebone Pawplexer Bacon Medium 40PK', available: 27, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '831244', description: 'Benebone Product', available: 166, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '832244', description: 'Benebone Product', available: 211, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '833244', description: 'Benebone Product', available: 231, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '834244', description: 'Benebone Product', available: 123, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '838244', description: 'Benebone Product', available: 127, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '838244ML', description: 'Benebone Product', available: 110, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '838500', description: 'Benebone Product', available: 625, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '840244', description: 'Benebone Product', available: 81, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '840244ML', description: 'Benebone Product', available: 439, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '840500', description: 'Benebone Wishbone Chicken Small 50PK', available: 772, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '841244', description: 'Benebone Product', available: 342, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '842244', description: 'Benebone Product', available: 587, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '843244', description: 'Benebone Wishbone Venison Large 24/4PK', available: 260, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '845244', description: 'Benebone Wishbone Turkey Medium 24/4PK', available: 181, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '846244', description: 'Benebone Ring Turkey Medium 24/4PK', available: 85, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '847244', description: 'Benebone Bone Turkey Medium 24/4PK', available: 86, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '850244', description: 'Benebone Pawplexer Bacon Large 24/4PK', available: 3, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '850250', description: 'Benebone Product', available: 25, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '851244', description: 'Benebone Product', available: 575, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '851244P', description: 'Benebone Product', available: 16, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '855244', description: 'Benebone Product', available: 612, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '855244P', description: 'Benebone Product', available: 71, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '860244', description: 'Benebone Product', available: 968, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '860244ML', description: 'Benebone Product', available: 93, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '860350', description: 'Benebone Product', available: 1329, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '860350X', description: 'Benebone Product', available: 882, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '861244', description: 'Benebone Product', available: 60, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '861350', description: 'Benebone Product', available: 203, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '862244', description: 'Benebone Product', available: 64, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '862350', description: 'Benebone Product', available: 230, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '870244', description: 'Benebone Product', available: 1035, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '870244ML', description: 'Benebone Product', available: 458, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '870400', description: 'Benebone Product', available: 2604, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '871244', description: 'Benebone Wishbone Peanut Large 24/4PK', available: 101, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '871244ML', description: 'Benebone Product', available: 81, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '871400', description: 'Benebone Product', available: 1024, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '872244', description: 'Benebone Product', available: 129, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '872244ML', description: 'Benebone Product', available: 314, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '872400', description: 'Benebone Wishbone Chicken Large 40PK', available: 448, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '873244', description: 'Benebone Product', available: 283, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '873244ML', description: 'Benebone Product', available: 0, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '874244', description: 'Benebone Green Wishbone Bacon Eco Bone Medium 24/4PK', available: 67, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '874244ML', description: 'Benebone Product', available: 0, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '875244', description: 'Benebone Green Wishbone Bacon Eco Bone Large 24/4PK', available: 237, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '875244ML', description: 'Benebone Product', available: 0, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '876244', description: 'Benebone Product', available: 68, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '876244ML', description: 'Benebone Product', available: 105, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '876300', description: 'Benebone Wishbone Bacon Giant 30PK', available: 449, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '877244', description: 'Benebone Product', available: 52, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '877300', description: 'Benebone Product', available: 120, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '878244', description: 'Benebone Product', available: 69, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '878300', description: 'Benebone Product', available: 127, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '880244', description: 'Benebone Dental Chew Bacon Small 24/4PK', available: 76, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '880244ML', description: 'Benebone Product', available: 112, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '880300', description: 'Benebone Dental Chew Bacon Small 30PK', available: 189, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '881244', description: 'Benebone Dental Chew Peanut Small 24/4PK', available: 2, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '881300', description: 'Benebone Dental Chew Peanut Small 30PK', available: 67, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '882244', description: 'Benebone Dental Chew Chicken Small 24/4PK', available: 2, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '882300', description: 'Benebone Dental Chew Chicken Small 30PK', available: 228, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '890244', description: 'Benebone Dental Chew Bacon Large 24/4PK', available: 53, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '890244ML', description: 'Benebone Product', available: 70, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '890300', description: 'Benebone Dental Chew Bacon Large 30PK', available: 200, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '891244', description: 'Benebone Dental Chew Peanut Large 24/4PK', available: 46, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '891300', description: 'Benebone Dental Chew Peanut Large 30PK', available: 71, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '892244', description: 'Benebone Dental Chew Chicken Large 24/4PK', available: 47, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '892300', description: 'Benebone Dental Chew Chicken Large 30PK', available: 116, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '901244', description: 'Lumabone Stick Small 24/4PK', available: 17, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '901246EF', description: 'Benebone Product', available: 1, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '902244', description: 'Lumabone Stick Medium 24/4PK', available: 224, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '904244', description: 'Lumabone Ring-Stuffer Bacon Small 24/4PK', available: 92, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '905244', description: 'Lumabone Ring-Stuffer Bacon Medium 24/4PK', available: 110, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '905246EF', description: 'Benebone Product', available: 3, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '906244', description: 'Lumabone Ring-Stuffer Bacon Large 24/4PK', available: 76, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '908244', description: 'Lumabone Wishbone Bacon Medium 24/4PK', available: 1108, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '913320F', description: 'Benebone Product', available: 1692, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '914244', description: 'Lumabone Ring-Stuffer Beef Small 24/4PK', available: 25, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '915244', description: 'Lumabone Ring-Stuffer Beef Medium 24/4PK', available: 88, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '916244', description: 'Lumabone Ring-Stuffer Beef Large 24/4PK', available: 47, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '920244', description: 'Lumabone Wag-n-Roll Bacon Medium 24/4PK', available: 112, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '928244', description: 'Lumabone Wishbone Bacon Small 24/4PK', available: 1177, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '960244', description: 'Lumabone Dental Chew Bacon Medium 24/4PK', available: 93, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '960246EF', description: 'Benebone Product', available: 2, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '970244', description: 'Lumabone Wishbone Bacon Large 24/4PK', available: 208, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '971244', description: 'Lumabone Bulkster Bacon Small 24/4PK', available: 86, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '972244', description: 'Lumabone Bulkster Bacon Medium 24/4PK', available: 141, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '973244', description: 'Lumabone Bulkster Bacon Large 24/4PK', available: 43, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '974244', description: 'Lumabone Bulkster Bacon Giant 24/4PK', available: 16, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '980244', description: 'Lumabone Dental Chew Bacon Small 24/4PK', available: 66, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '981244', description: 'Lumabone Bulkster Beef Small 24/4PK', available: 60, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '982244', description: 'Lumabone Bulkster Beef Medium 24/4PK', available: 79, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '982246EF', description: 'Benebone Product', available: 47, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '983244', description: 'Lumabone Bulkster Beef Large 24/4PK', available: 14, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '984244', description: 'Lumabone Bulkster Beef Giant 24/4PK', available: 19, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '990060', description: 'Lumabone 3-Pack WB/WG/SK Bacon Medium', available: 1519, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '991060', description: 'Lumabone 3-Pack WB/DC/RS Bacon Medium', available: 1162, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: '992080', description: 'Lumabone 4-Pack WB/RS/DC/SK Bacon Medium', available: 1723, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: 'BB-PM0', description: 'Benebone Product', available: 7993, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: 'BB-PM2', description: 'Benebone Product', available: 0, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: 'BB-PM4', description: 'Benebone Product', available: 5400, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: 'BB-PM5', description: 'Benebone Product', available: 2755, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: 'CTN03', description: 'Benebone Product', available: 906, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: 'CTN05', description: 'Benebone Product', available: 615, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: 'CTN07', description: 'Benebone Product', available: 1080, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: 'CTN08', description: 'Benebone Product', available: 16152, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: 'CTN08 SHIPPER', description: 'Benebone Product', available: 1859, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: 'U111', description: 'Benebone Product', available: 1439, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: 'U112', description: 'Benebone Product', available: 13758, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: 'U113', description: 'Benebone Product', available: 837, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: 'U121', description: 'Benebone Product', available: 4759, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: 'U131', description: 'Benebone Product', available: 960, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: 'U141', description: 'Benebone Product', available: 1041, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: 'U150', description: 'Benebone Product', available: 3844, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: 'U151', description: 'Benebone Product', available: 2095, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: 'U410', description: 'Benebone Product', available: 26540, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: 'U420', description: 'Benebone Product', available: 4768, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: 'U430', description: 'Benebone Product', available: 6760, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: 'U610', description: 'Benebone Product', available: 464, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: 'U620', description: 'Benebone Product', available: 2420, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: 'U630', description: 'Benebone Product', available: 1380, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: 'U801', description: 'Benebone Product', available: 1724, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: 'U803', description: 'Benebone Product', available: 3290, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: 'U808', description: 'Benebone Product', available: 10478, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: 'U818', description: 'Benebone Product', available: 1350, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: 'U820', description: 'Benebone Product', available: 290, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: 'U826', description: 'Benebone Product', available: 1360, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: 'U827', description: 'Benebone Product', available: 2580, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: 'U828', description: 'Benebone Product', available: 10900, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: 'U829', description: 'Benebone Product', available: 1990, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: 'U838', description: 'Benebone Product', available: 6450, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: 'U860', description: 'Benebone Product', available: 10507, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: 'U863', description: 'Benebone Product', available: 4250, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: 'U864', description: 'Benebone Product', available: 2700, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: 'U865', description: 'Benebone Product', available: 2650, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: 'U870', description: 'Benebone Product', available: 8057, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: 'U871', description: 'Benebone Product', available: 2495, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: 'U872', description: 'Benebone Product', available: 1795, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
  { sku: 'U880', description: 'Benebone Product', available: 660, avgMonthlySales: 0, mos: 0, amountToReachSS: 0, segmentBand: 'Unknown', casePack: 24 },
]

const factories = [
  { id: 'aim', mosThreshold: 1.5 },
  { id: 'midbury', mosThreshold: 2.0 },
  { id: 'ltm', mosThreshold: 2.0 },
  { id: '201', mosThreshold: 2.0 },
  { id: 'bennett', mosThreshold: 2.0 },
  { id: 'dmg', mosThreshold: 2.0 },
  { id: 'coltoys', mosThreshold: 2.0 },
  { id: 'lovingpets', mosThreshold: 2.0 }
]

export default function handler(req, res) {
  if (req.method !== 'GET') {
    return res.status(405).json({ error: 'Method not allowed' })
  }

  try {
    // Generate alerts based on MOS thresholds
    const alerts = []
    mockInventoryData.forEach(sku => {
      factories.forEach(factory => {
        if (sku.mos <= factory.mosThreshold) {
          alerts.push({
            id: `${sku.sku}-${factory.id}`,
            sku: sku.sku,
            description: sku.description,
            factory: factory.id,
            factoryId: factory.id,
            mos: sku.mos,
            threshold: factory.mosThreshold,
            onHand: sku.available,
            avgMonthlySales: sku.avgMonthlySales,
            amountToReachSS: sku.amountToReachSS,
            priority: sku.mos < 1 ? 'critical' : 'warning',
            segmentBand: sku.segmentBand
          })
        }
      })
    })

    res.status(200).json({
      skus: mockInventoryData,
      alerts: alerts,
      lastUpdate: new Date().toISOString()
    })
  } catch (error) {
    console.error('Inventory API error:', error)
    res.status(500).json({ error: 'Failed to load inventory data' })
  }
}
